### PR TITLE
Revert "fix first_search"

### PR DESCRIPTION
**Pull request by ddugovic**
This reverts commit 6400e782f26c59c1552a9d9fbd55bb2d826f8d64.

### CODE REVIEW

**Comment by gbtami** [comment]
This commit causes to send "st 2" after "level" and engines can lose on time in short time control games thinking they have to think 2 sec on every move.

From http://hgm.nubati.net/CECP.html
level MOVESPERSESSION BASETIME INCREMENT
st T

Two mutually exclusive commands (erasing each other's effect) for specifying the time control. In 'level' either MOVESPERSESSION equals 0 (for incremental and sudden-death TC), or INCREMENT is 0 (for classical TC). With 'st' the time control will be T seconds per move (not accumulating leftovers). The BASETIME parameter is in minutes, and can have the MIN:SEC notation. INCREMENT and T are in seconds. Engines are encouraged to understand a floating-point number for the INCREMENT, or at least to not choke on it.

**Comment by ddugovic** [comment]
What happens after a subsequent:

https://github.com/ddugovic/lichess-bot/blob/fcf0d450209b5715775c953c0acec411f3ef1550/engine_wrapper.py#L153-L161

**Comment by gbtami** [comment]
Time control and clock are two different thing. If a CECP engine got "st T" it will ignore time/otime because it was told that it have to use T for all moves.

**Comment by ddugovic** [comment]
OK, what if a subsequent `level` command were sent (after a best move is received)?

**Comment by gbtami** [comment]
I think both "st 2" then "level" or "level" then "level" can do the job. Maybe the latter is better  regarding in ultrabullet/bullet games thinking 2 sec on the very first move may be luxury.

**Comment by ZirconiumX** [comment]
I think `st 2`, `go` then issuing a `level` afterwards is the most idiomatic way to do it.

On the other hand, XBoard engines tend to be much looser with the specification than UCI engines, and some workarounds may be required at some point.

**Comment by ddugovic** [comment]
I agree with all comments and will update this PR to use `level` twice (and not use `st`) since XBoard engines likely support that protocol usage.

**Comment by gbtami** [comment]
st 2 on first move in an ultrabullet game seems rather big handicap.

**Comment by ZirconiumX** [comment]
Then just pass `game` to `first_search` and scale first move with time control, perhaps?

**Comment by ornicar** [comment]
So do I merge this?

**Comment by ZirconiumX** [comment]
I mean, for Dorpsgek, it'd actually search for only a third of a second with that TC, so it should be fine.

**Comment by ddugovic** [comment]
@ornicar Looks good to me & I hear no objections to merging it.  It seems to issue correct commands although my `gnuchess` I'm testing with isn't respecting the `xboard` protocol.

**Comment by ddugovic** [comment]
Successfully tested at https://listage.ovh/CpIv3rn9

**Comment by gbtami** [comment]
Works OK with PyChessBot also.

**Pull request merged**
