### PR TITLE
Support for polyglot book

### PR DESCRIPTION
**Pull request by tttony**
Added support for engines that doesn't have book options

Tested in my UCI engine and it's working!

### CODE REVIEW

**Comment by careless25** [comment]
Can you fix the merge conflicts and we can get this merged in

**Comment by tttony** [comment]
Conflict solved! But I'm not in home, I can't tested it now

**Comment by tttony** [comment]
Sorry, added a last update

**Comment by tttony** [comment]
Updated with recent changes

**Comment by tttony** [comment]
phewww for now is up to date with the 0.8, I'm testing it right now and it's working

**Comment by gbtami** [comment]
Tested it with PyChessBot. It works great!

**Pull request merged**
