### PR TITLE
Fix #96 No time control command sent to xboard engine

### LINKED ISSUE #96: No time control command sent to xboard engine
The latest revert-fix-first-search patch fixed time control handling when xboard engine doesn't use polyglot book but unfortunately introduced new bug (no time control sent at all) when they do use it:
```
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "GET /api/bot/game/stream/d3p0IL08 HTTP/1.1" 200 None
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << xboard
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << protover 2
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << post
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << easy
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << ping 123
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> # PyChess 0.99.1 [pypy3 3.5.3]
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> feature ping=1 setboard=1 playother=1 san=1 usermove=1 time=1 draw=1 sigint=0 sigterm=0 reuse=1 analyze=1 myname="PyChess 0.99.1" variants="normal,wildcastle,nocastle,fischerandom,crazyhouse,losers,suicide,giveaway,horde,atomic,racingkings,kingofthehill,3check,asean,cambodian,makruk,sittuyin" colors=0 ics=0 name=0 pause=0 nps=0 debug=1 memory=0 smp=0 egt="gaviota" option="skipPruneChance -slider 0 0 100"
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> feature done=1
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> pong 123
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << egtpath gaviota ../Gaviota/Gaviota
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << force
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << setboard rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1
+++ https://lichess.org/d3p0IL08/white Blitz vs Beige(1751)
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): lichess.org
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/d3p0IL08/move/g1f3 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/d3p0IL08/move/c2c4 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/d3p0IL08/move/e2e3 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/d3p0IL08/move/e3d4 HTTP/1.1" 200 None
DEBUG:requests.packages.urllib3.connectionpool:https://lichess.org:443 "POST /api/bot/game/d3p0IL08/move/g2g3 HTTP/1.1" 200 None
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << force
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << setboard rn1qkbnr/pp2pppp/8/5b2/2Pp4/5NP1/PP1P1P1P/RNBQKB1R w KQkq - 1 6
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << time 31198.0
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << otim 29156.0
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> << go
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> # remaining moves estimate=69.55331928214001
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> # Searching to depth 10 without timelimit
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 1 -24 3 50 c5
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 2 -47 28 449 Nh4 Be4
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 3 -18 146 2407 Bg2 d3 O-O
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 4 -69 642 13281 Bg2 Bxb1 Qa4+ Nc6 Rxb1
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 5 -18 1525 50161 Bg2 Nc6 d3 e5 O-O
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 6 -36 5377 260090 Bg2 Nc6 d3 Qa5+ Bd2 Qd8
DEBUG:chess.engine:<PopenProcess at 0x7fc564f74b00 (pid=31042)> >> 7 -13 14976 1270843 Bg2 d3 O-O Bg4 Qb3 b6 Qd1
^C--- https://lichess.org/d3p0IL08/white Game over
```

### PR DESCRIPTION
**Pull request by gbtami**

### CODE REVIEW

**Comment by ddugovic** [comment]
The entire purpose of passing the `game` object to `first_search` was to set the time control...?

**Comment by gbtami** [comment]
@ddugovic  Fixed. Thx!

**Comment by ddugovic** [comment]
Oh, I see, if `play_first_book_move` was used instead, the TC wouldn't be set.  Nice fix.

**Comment by careless25** [comment]
Can someone test this?

**Comment by gbtami** [comment]
I'v tested it with PychessBot with using polyglot book and without using it. It worked OK.
@ZirconiumX can you test this also, please?

**Comment by ZirconiumX** [comment]
This appears to be broken? I put it on production yesterday and have a string of aborted games.

**Comment by gbtami** [comment]
Seems your problem (https://github.com/careless25/lichess-bot/issues/99) is unrelated to this PR

**Comment by gbtami** [comment]
@careless25 PyChessBot had no problem in last 3 day using this fix.
May I ask you to merge this PR please?

**Comment by careless25** [comment]
@ZirconiumX When you say broken...what was the error? 

@gbtami will do by end of day.

**Comment by gbtami** [comment]
@careless25 @ZirconiumX problem with current master is https://github.com/careless25/lichess-bot/issues/99

**Comment by nanliouhu** [comment]
# lichess OAuth2 Token
url: "https://lichess.org/"  # lichess base URL

engine:                      # engine settings
  dir: "./engines/"          # dir containing engines, relative to this project
  name: "engine_name"        # binary name of the engine to use
  protocol: "uci"            # "uci" or "xboard"
#  weights: "latest.txt"     # only if the engine is lczero
#  threads: 1                # only if the engine is lczero
#  gpu: 0                    # only if the engine is lczero
  polyglot: false            # activate polyglot book
  polyglot_book: "book.bin"  # book file name, must be in engine.dir
  polyglot_max_depth: 8      # half move max depth
  polyglot_min_weight: 1     # best move weight
  polyglot_random: true      # select move randomly otherwise select by min weight
  silence_stderr: false      # some engines (yes you, leela) are very noisy

ucioptions:                  # arbitrary UCI options passed to the engine
  Move Overhead: 100         # increase if your bot flags games too often
#  Threads: 4
#  Hash: "4096"
#  Book File: "engines/book.bin"

xboardoptions:
#  cores: "4"
#  memory: "4096"
#  egtpath:                   # dir containing egtb, relative to this project
#    gaviota: "Gaviota path"
#    nalimov: "Nalimov Path"
#    scorpio: "Scorpio Path"
#    syzygy: "Syzygy Path"

max_concurrent_games: 1      # number of games to play simultaneously
sort_challenges_by: "best"   # possible values: "best", "first"
abort_time: 20               # time to abort a game in seconds when there is no activity
accept_bot_challenges: true  # accepts challenges coming from other bots

supported_variants:          # chess variants to accept (http://lichess.org/variant)
  - standard
#  - fromPosition
#  - antichess
#  - atomic
#  - chess960
#  - crazyhouse
#  - horde
#  - kingOfTheHill
#  - racingKings
#  - threeCheck

supported_tc:                # time controls to accept
  - ultraBullet
  - bullet
  - blitz
  - rapid
#  - classical
#  - correspondence

supported_modes:             # game modes to accept
  - casual                   # unrated games
  - rated                    # rated games - must comment if the engine doesn't try to win

print_engine_stats: false    # print engine stats on each move

**Comment by gbtami** [comment]
@nanliouhu ?

**Comment by careless25** [comment]
@gbtami I am going to merge this into `next`. And then `next` into `master`.

**Pull request merged**
