### PR TITLE
display winrate

### PR DESCRIPTION
**Pull request by wakamex**
show winrate calculated from cp (inverse from here: https://github.com/glinscott/leela-chess/blob/27bc580e57a8e01d4d137ed65c0f325c4b7b4661/src/UCTSearch.cpp)

### CODE REVIEW

**Comment by ddugovic** [comment]
Stockfish has a different formula: https://github.com/ornicar/lila/issues/1494

**Comment by wakamex** [comment]
maybe that one could be dded to the main branch, while this one would fit under the leela branch. also stockfish estimates its winrate as a byproduct, while leela trains directly on it, estimating cp as a byproduct, making it more relevant in her case.

**Comment by ddugovic** [comment]
Indeed, Leela's estimate should be more accurate, whereas SF estimates need to be retrained periodically.

**Comment by careless25** [comment]
Can you resolve the conflict?

**Comment by careless25** [comment]
Closing. I fixed it in the new version.

**Pull request closed without merging**
