### PR TITLE
Do not retry on HTTPError due to opponent abort #125

### PR DESCRIPTION
**Pull request by ddugovic**
This won't prevent the HTTP 400 response, but should reduce the number of retries.

### CODE REVIEW

**Comment by drbeco** [comment]
I believe this is too radical. Internet in general needs a bit of redundancy. Ok that 12 tries is too much, but if I'm not reading this wrong, it would abort at the first error.

Maybe let it try something like 3 tries with an interval of a (few) second in between?

**Comment by ddugovic** [comment]
Why is there a need for redundancy when the server returns an HTTP 400 response?  HTTP 400 means the client made an error.

**Comment by drbeco** [comment]
You may be right, I'm being over defensive. Without reading further the code I can't say, but surely it is good to double check if this error is issued only in such controlled way.

**Comment by ddugovic** [comment]
What are your thoughts on:
https://github.com/careless25/lichess-bot/blob/63568da558e46360990843e079ecbcf05276d568/lichess.py#L42

which is currently deployed on all `lichess-bot` instances and appears to be based upon the example provided by `backoff` itself?
https://github.com/litl/backoff/commit/cc8dc948ac7bbf5f2af3926545285ece8aba1491#diff-88b99bb28683bd5b7e3a204826ead112R49

**Comment by ddugovic** [comment]
@drbeco Given that this PR only handles `HTTPError` and only for error codes below `500` and is based upon the above example, is there any objection to merging this (so @ornicar 's server doesn't get blasted with ~10 retries against `HTTP 400` responses every time an opponent aborts)?

**Comment by ddugovic** [comment]
@drbeco @careless25 Please review as this should reduce 90% of the traffic to the Lichess server in cases where the opponent has aborted or resigned out of turn.

**Pull request merged**
