### PR TITLE
Add cwd to chess.xboard.popen_engine() to let Hiarcs engine run

### PR DESCRIPTION
**Pull request by gbtami**

### CODE REVIEW

**Comment by ddugovic** [comment]
I'm not a python expert (I don't remember `cwd`), however I remember years ago seeing that something like this (separating the path and name) is idiomatic.

**Comment by gbtami** [comment]
Yes. See https://docs.python.org/3/library/subprocess.html#popen-constructor
"If cwd is not None, the function changes the working directory to cwd before executing the child."

**Comment by careless25** [comment]
Tested this and it doesn't make a difference on windows version of Hiarcs.

**Comment by gbtami** [comment]
Interesting. When I'm not in the engines directory, starting hiarcs immediately quits:
```
C:\lichess-bot-gbtami>dir engines
 Volume in drive C has no label.
 Volume Serial Number is D0B8-A573

 Directory of C:\lichess-bot-gbtami\engines

2018. 12. 31.  15:28    <DIR>          .
2018. 12. 31.  15:28    <DIR>          ..
2015. 03. 05.  17:27         1 891 328 Hiarcs14WCSC.exe
2018. 12. 31.  15:23                24 README.md
               2 File(s)      1 891 352 bytes
               2 Dir(s)  17 311 580 160 bytes free

C:\lichess-bot-gbtami>engines\Hiarcs14WCSC.exe
HIARCS by Mark John Uniacke
Copyright (c) 1992-2015 Mark Uniacke, Applied Computer Concepts Ltd. All rights reserved.

C:\lichess-bot-gbtami>cd engines

C:\lichess-bot-gbtami\engines>Hiarcs14WCSC.exe
HIARCS by Mark John Uniacke
Copyright (c) 1992-2015 Mark Uniacke, Applied Computer Concepts Ltd. All rights reserved.
uci
id name HIARCS 14 WCSC
id author Mark John Uniacke
option name Licensed To type combo default gbtami@gmail.com var gbtami@gmail.com
option name OwnBook type check default true
option name Book Learning type check default true
option name Book Mode type combo default Tournament var Wild var Surprise var Dynamic var Tournament
option name Book Positions type combo default 7359978 var 7359978
option name Book Status type combo default Hiarcs14bBook.hcs OK var Hiarcs14bBook.hcs OK
option name Use Tablebases type combo var Often var Normally var Rarely var Never default Normally
option name Swindle Opponent type check default true
option name NalimovCache type spin min 1 max 1024 default 32
option name NalimovPath type string default
option name Hash type spin min 1 max 2048 default 128
option name Clear Hash type button
option name Retain Hash type check default true
option name Position Learning type check default true
option name Optimistic Search type check default true
option name Combinations type check default true
option name Hiarcs Draw Value type spin min -100 max 100 default 0
option name Search Selectivity type spin min 0 max 7 default 7
option name Playing Style type combo default Active var Active var Aggressive var Solid
option name Hyper-Modern Play type check default true
option name GUI Time Lag type check default false
option name AutoSave PGN type check default true
option name UCI_Elo type spin min 750 max 3081 default 2315
option name UCI_LimitStrength type check default false
option name UCI_AnalyseMode type check default false
option name UCI_SearchMoves type check default true
option name UCI_ShowCurrLine type check default false
option name UCI_Chess960 type check default false
option name MultiPV type spin min 1 max 127 default 1
option name Ponder type check default true
option name UCI_EngineAbout type string default HIARCS 14 WCSC (05/03/15) Copyright (c) 1991-2015 Applied Computer Concepts Ltd.  All rights reserved. 2011 World Chess Software Champion.
registration checking
registration ok
option name Licensed To type string default gbtami@gmail.com
uciok
```

**Pull request closed without merging**
