### PR TITLE
add increment setting

### PR DESCRIPTION
**Pull request by quillford**

### CODE REVIEW

**Comment by careless25** [comment]
How does someone specify any/infinite increment?

**Comment by quillford** [comment]
180 seconds is the max on lichess so 180 or above will be unlimited. That should definitely be added to the comment and maybe it should be the default.

**Comment by ddugovic** [comment]
How does someone specify a minimum increment?

**Comment by careless25** [comment]
Can you make the changes @ddugovic and I suggested. Thanks :)

**Comment by quillford** [comment]
Alright. I added a min increment setting and made the default more sensible.

**Pull request merged**
