### PR TITLE
Enable UCI variants except From Position

### PR DESCRIPTION
**Pull request by ddugovic**
There might be better ways to write this code, but it's deployed at https://lichess.org/@/GodelEscherBot

### CODE REVIEW

**Comment by careless25** [comment]
Would you know how to add support for it for Xboard?

**Comment by ZirconiumX** [comment]
From Position support isn't actually hard from the protocol point of view. Hell, it's basically transparent to the *Engine classes, because they just get fed a position and told to make do.

**Comment by gbtami** [comment]
Updated my https://github.com/careless25/lichess-bot/pull/34 PR with xboard variant support. It works after this PR applied and after https://github.com/niklasf/python-chess/pull/272 applied also in python-chess. You can try it playing with https://lichess.org/@/PyChessBot :)

**Comment by careless25** [comment]
@ddugovic can you fix the merge conflicts. 
Also, Lets wait until we have Xboard support before we merge this in.

**Comment by gbtami** [comment]
@careless25 variant support now merged into python-chess. xboard variant support for lichess-bot is in #34 PR, but it assumes _this_ PR merged first.

**Comment by ddugovic** [comment]
This is how I resolved the merge conflict:
https://github.com/careless25/lichess-bot/pull/36/files#diff-5bc02cefb3ea9e27f1a6776eabd1935dR91

**Pull request merged**
