### PR TITLE
Use the same session for Lichess API requests

### PR DESCRIPTION
**Pull request by fli**
Changes non-streaming Lichess requests to use a Session object to improve performance with connection pooling.

Future changes can move the auth header into the Session object too, but I'll keep this PR small.

### CODE REVIEW

**Comment by fli** [comment]
I'm not sure whether it is the result of this change, or if it's Lichess rate limiting or something else, but sometimes I get the following error. I thought it was fixed by the HTTPAdapter but maybe not.

```Traceback (most recent call last):
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francis/miniconda3/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/francis/miniconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/home/francis/miniconda3/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/francis/lichess-bot/logging_pool.py", line 16, in __call__
    result = self.__callable(*args, **kwargs)
  File "main.py", line 109, in play_game
    li.make_move(game.id, best_move)
  File "/home/francis/lichess-bot/lichess.py", line 48, in make_move
    return self.get_json(self.session.post(url, headers=self.header))
  File "/home/francis/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/francis/miniconda3/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))```

**Comment by careless25** [comment]
@fli that looks like something wrong with the code above. I have been online on Lichess for a few hours now without any errors.

**Comment by fli** [comment]
@careless25 I'll have another look later. Just realised it could be my home internet being spotty

**Comment by fli** [comment]
I think it was Lichess throttling me when I changed it to use a Session object. I've added some code to recover from that and other connection problems. Still needs testing.

**Comment by ornicar** [comment]
I like it. Testing now.

Bots are subject to lichess API rate limiting and can receive `429` responses. In which case they should wait a minute before resuming activity.

**Comment by ornicar** [comment]
It works. IMO the best course of action to know if it works on Windows is to merge it as a single squashed commit, that can be easily reverted when it fails on Windows.

**Pull request merged**
