### PR TITLE
Graceful exit

### PR DESCRIPTION
**Pull request by smartchessguiapp**
Allows the user to gracefully exit the application by typing "x" or "X" then pressing ENTER.

Adresses complaints about stopping the application using Ctrl+C being cumbersome.

### CODE REVIEW

**Comment by ornicar** [comment]
Can we have that by pressing Ctrl+c instead?

**Comment by gbtami** [comment]
I suggest to use this pattern instead:
```
import signal

def signal_handler(signal, frame):
        print('You pressed Ctrl+C!')
signal.signal(signal.SIGINT, signal_handler)
```

**Comment by typescriptstudies** [comment]
This generates a long error log. My solution prints "exiting lichess-bot...", then exits smoothly without error messages.

**Comment by smartchessguiapp** [comment]
This generates a long error log. Not graceful enough.

**Comment by careless25** [comment]
Can you implement it as `CTRL+C` like @ornicar mentioned?

**Comment by HalmonLui** [comment]
since ctrl-c will always raise a KeyboardInterrupt, instead of using signal you could use a try/except and listen for a KeyboardInterrupt:
```python
def user_input(prompt): 
  try: 
    return input(prompt)
  except KeyboardInterrupt:
    print("If you want to exit, press ctrl-c again to quit")
  return input(prompt) 
```

**Comment by krs013** [comment]
@HalmonLui I think the trouble with that is that the program might not be in that thread when the signal is sent.

**Comment by smartchessguiapp** [comment]
https://github.com/careless25/lichess-bot/commit/359ad213dbcfac9ba2b84834dc0f096f08defd69

**Pull request closed without merging**
