### PR TITLE
Removed deceptious st (time control) command caused engine losing on …

### PR DESCRIPTION
**Pull request by gbtami**
…time in #72

### CODE REVIEW

**Comment by ZirconiumX** [comment]
This is not how it should have been fixed, I think.

Instead, the code should call `pre_game` (which should be renamed) after the first move, so that the `level` command overrides the `st` command.

**Comment by gbtami** [comment]
Telling the truth this whole "go movetime 2000" (and xboard workaround attempts) should be dropped and apply auto abort on timeout for all BOT games.

**Comment by ZirconiumX** [comment]
My own solution would be simply to require polyglot books, and then use those for at the very least the first move.

**Comment by ddugovic** [comment]
How do polyglot books work for variants?

**Comment by ZirconiumX** [comment]
As long as people can agree on a unique set of hash keys for a given
variant that are sufficiently random, Polyglot format can be used for
variants, too. It's just a key/value dictionary, with a weight.

**Pull request merged**
