### PR TITLE
XBoard option compatibility layer

### PR DESCRIPTION
**Pull request by ZirconiumX**
This tries to convert UCI options into the equivalent XBoard commands.

### CODE REVIEW

**Comment by ZirconiumX** [comment]
@careless25 @ornicar Can you check this?

**Comment by careless25** [comment]
@ZirconiumX Have you tested it?

**Comment by ZirconiumX** [comment]
Rebased and squashed to master.

**Comment by careless25** [comment]
Can you fix the merge conflicts?

**Comment by ZirconiumX** [comment]
Done.

**Comment by careless25** [comment]
Can anyone test this? Or link me to a xboard engine?

**Comment by mroh69** [comment]
how about adding something like "xboardoptions" to the config instead of trying to convert (and guess) the uci options to xboard?

**Comment by ZirconiumX** [comment]
That feels like trying to reinvent the wheel, because having separate
xboard/UCI sections will cause code duplication.

On 21 Apr 2018 21:27, "Michael Rohleder" <notifications@github.com> wrote:

how about adding something like "xboardoptions" to the config instead of
trying to convert (and guess) the uci options to xboard?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/careless25/lichess-bot/pull/27#issuecomment-383327321>,
or mute the thread

**Comment by mroh69** [comment]
I think its much less code duplication. maybe its bit duplication in the config, but the code is much less.
for example, the config could look like this:

```yml
# this holds the option for uci *or* xboard
# user has to comment out the options he doesnt want (uci or xboard)
engineoptions:     
  # commented as current "ucioptions:"
  # Threads: 2
  # Hash: 2048
  # xboard options
  cores: 2
  memory: 2048
  egtpath: "path"
  some other option: "bla"
```

and in the code its just (as for uci)
```python
engine.xboard.option(CONFIG['engineoptions'])
```

instead of
```python
if option == "could be that name":
  engine.xboard.egtpath(value)
if option == "could be other name"
  engine.xboard.egtpath(value)
if option == "Threads"
  engine.xboard.memory(value)
if option == "Move Overhead"   # uci name in some engines
...
if option == "Overhead"   # uci name of other engines
...
if option == "an option I dont know"
...
etc pp for so many uci options in so many variants...
```

**Comment by careless25** [comment]
+1 For @mroh69 suggestion. Keep the engine config separate instead of the if statement conversions.

**Comment by ZirconiumX** [comment]
Uh, no. That's not even slightly true, and my code should demonstrate that.

If I use a separate `xboardoptions` config, then I *still* need to use if statement conversions to convert from options to XBoard commands.

It gains nothing other than the config being bigger.

**Comment by gbtami** [comment]
@ZirconiumX can you update this patch please? I'm using  it and I hope maintainers will merge it :)

**Comment by ZirconiumX** [comment]
I kinda ballsed it up, but I think I know how to fix it; first I need to
get home from school though. Hopefully Thibault and Shail can avoid giving
me another 60 patches to rebase against for a few hours.

**Comment by ZirconiumX** [comment]
This should be cleaner, even if it took manually editing a patch file to get something that looked reasonable.

**Comment by gbtami** [comment]
Thx!

**Pull request merged**
